# Generated by Django 4.2.9 on 2024-02-02 21:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_remove_post_no_of_likes_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='made_one',
            field=models.ManyToManyField(blank=True, related_name='made_one', to=settings.AUTH_USER_MODEL),
        ),
    ]
