# Generated by Django 4.2.9 on 2024-02-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_category_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='concept',
            field=models.TextField(verbose_name='Product Description:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='document',
            field=models.TextField(verbose_name='Build Details'),
        ),
    ]
