# Generated by Django 4.2.9 on 2024-02-10 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_issues_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'about'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name_plural': 'feedback'},
        ),
        migrations.AlterModelOptions(
            name='issues',
            options={'verbose_name_plural': 'issues'},
        ),
    ]
