# Generated by Django 4.2.9 on 2024-02-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_about_options_alter_feedback_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='priority',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
