# Generated by Django 4.2.9 on 2024-02-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_about_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['order'], 'verbose_name_plural': 'about'},
        ),
        migrations.RenameField(
            model_name='about',
            old_name='priority',
            new_name='order',
        ),
        migrations.AddField(
            model_name='about',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
